[tool.poetry]
name = "varfxi"
version = "0.0.2"
description = "Volatility based estimation for FX interventions"
authors = ["romainlafarguette <romain.lafarguette@gmail.com>", "amineraboun <amineraboun@gmail.com>"]
repository ="https://github.com/romainlafarguette/varfxi"
homepage  ="https://github.com/romainlafarguette/varfxi"

readme = "README.md"
keywords = ["var", "garch"]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.9"
pandas = "^1.5.3"
numpy = "^1.24.2"
arch = "^5.3.1"
matplotlib = "^3.7.1"

# Dev dependencies
seaborn = "^0.12.2"
tqdm = "^4.65.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
pytest-cov = "^3.0"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]

[tool.pylint]
   [tool.pylint."FORMAT"]
   max-line-length = 120
   max-args = 5
   
# Documentation dependencies
[tool.poetry.group.docs]
optional = true
[tool.poetry.group.docs.dependencies]
Sphinx = "^5.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"